/**
 * 公共代理节点
 */
export const PUBLIC_PROXY_LIST: string[] = [
  'https://00.worker-proxy.asia',
  'https://01.worker-proxy.asia',
  'https://02.worker-proxy.asia',
  'https://03.worker-proxy.asia',
  'https://04.worker-proxy.asia',
  'https://05.worker-proxy.asia',
  'https://06.worker-proxy.asia',
  'https://07.worker-proxy.asia',
  'https://08.worker-proxy.asia',
  'https://09.worker-proxy.asia',
  'https://10.worker-proxy.asia',
  'https://11.worker-proxy.asia',
  'https://12.worker-proxy.asia',
  'https://13.worker-proxy.asia',
  'https://14.worker-proxy.asia',
  'https://15.worker-proxy.asia',

  'https://00.net-proxy.asia',
  'https://01.net-proxy.asia',
  'https://02.net-proxy.asia',
  'https://03.net-proxy.asia',
  'https://04.net-proxy.asia',
  'https://05.net-proxy.asia',
  'https://06.net-proxy.asia',
  'https://07.net-proxy.asia',
  'https://08.net-proxy.asia',
  'https://09.net-proxy.asia',
  'https://10.net-proxy.asia',
  'https://11.net-proxy.asia',
  'https://12.net-proxy.asia',
  'https://13.net-proxy.asia',
  'https://14.net-proxy.asia',
  'https://15.net-proxy.asia',
];
